import { describe, expect, it } from "vitest";

import {
  AUTHORED_ALBANY_GREENWAY_EVENT_ID,
  AUTHORED_ALBANY_MARKET_EVENT_ID,
  AUTHORED_LOCAL_EVENT_LEGACY_DEFINITIONS,
} from "../../src/world/local_event_scene_legacy.js";
import {
  AUTHORED_ALBANY_CAMPUS_JOB_ID,
  AUTHORED_ALBANY_CIVIC_JOB_ID,
  AUTHORED_ALBANY_GREENWAY_JOB_ID,
  AUTHORED_ALBANY_MARKET_JOB_ID,
  AUTHORED_ALBANY_STATION_JOB_ID,
  AUTHORED_ALBANY_WORKS_JOB_ID,
  AUTHORED_LOCAL_JOB_LEGACY_DEFINITIONS,
  authoredLocalJobLegacyDefinitionsForSourceWorldHash,
} from "../../src/world/local_job_scene_legacy.js";
import {
  AUTHORED_ALBANY_CAMPUS_GENERIC_PREDECESSOR_WORLD_HASHES,
  AUTHORED_ALBANY_CAMPUS_PREDECESSOR_WORLD_HASH,
  AUTHORED_ALBANY_GREENWAY_GENERIC_PREDECESSOR_WORLD_HASHES,
  AUTHORED_ALBANY_GREENWAY_PREDECESSOR_WORLD_HASH,
  AUTHORED_ALBANY_MARKET_GENERIC_PREDECESSOR_WORLD_HASHES,
  AUTHORED_ALBANY_MARKET_PREDECESSOR_WORLD_HASH,
  AUTHORED_ALBANY_STATION_GENERIC_PREDECESSOR_WORLD_HASHES,
  AUTHORED_ALBANY_STATION_PREDECESSOR_WORLD_HASH,
  AUTHORED_ALBANY_WORKS_GENERIC_PREDECESSOR_WORLD_HASHES,
  OVERWORLD_AUTHORED_LOCAL_JOB_FIRST_SCENE_WORLD_HASH,
  OVERWORLD_AUTHORED_LOCAL_JOB_PREDECESSOR_WORLD_HASH,
  OVERWORLD_FIELD_TIMED_PREPARATION_PREDECESSOR_WORLD_HASH,
  WINTER_RETURN_DOCKET_GENERIC_PREDECESSOR_WORLD_HASHES,
  WINTER_RETURN_DOCKET_PREDECESSOR_WORLD_HASH,
} from "../../src/world/local_scene_legacy_sources.js";

const PRE_WORKS_HASHES = [
  "39d32c027d2e826f476dd299bb95cc3911994ec92b4fbf297be8d1216e5b6151",
  "b9416e3c43d9d54085ed9465b4d875811daebaf9834793d3f4a1ffca93b486c4",
  "cad75dafc291709f1d5c756dd70dd1002260bb06ca87d8e1e90aaf905f5f05c7",
  "1d12330f65743a8a2c124f9dae3cf145e6fdcbca9ec59a4c699ecd8757e8e47b",
  "07c2864bcad6eaadbd32e8ecff4460ddb7b63e6ed36b0316f4264aa866c1aa44",
  "2dbc97e2de8063be7b3a49fe3cb9108e8f80270d7d118efd781381659dba97c4",
  "742aa205a254b6f4382749fb63742caf1606024a1f6c044c2f433fda8dac6090",
  "f5835e15e6ccf5432ea6b39b87edf957ebc3ffb8a2518b48b46098f09aa92572",
  "2d10f959279a12166d521a774779acc46481fb6ff40d5982f9c955a30677a7b6",
  "1e74d32c28c3d563f6e8103034768506e25f13ff1f8e410b190cbb344589add8",
  "abd3b623a502b688a501bceae68994a4eb0e591d450420b5093532b5dae22179",
  "634fd4e93143343fd813edd9c59d3a8c098c0d78b94497cf689988492de154e3",
  "50350884ebb7d118849fca040256a19c0c63ed4bfe3353d4cd202ee7a6ba8e7f",
  "a2ddc6e9042a208f2821451f10b0152874ef55bc77b0f7801f3ea58591357474",
] as const;

const WORKS_HASHES = [...PRE_WORKS_HASHES, OVERWORLD_AUTHORED_LOCAL_JOB_PREDECESSOR_WORLD_HASH];
const CIVIC_HASHES = [
  ...WORKS_HASHES,
  OVERWORLD_AUTHORED_LOCAL_JOB_FIRST_SCENE_WORLD_HASH,
  WINTER_RETURN_DOCKET_PREDECESSOR_WORLD_HASH,
];
const CAMPUS_HASHES = [...CIVIC_HASHES, AUTHORED_ALBANY_CAMPUS_PREDECESSOR_WORLD_HASH];
const STATION_HASHES = [
  ...CAMPUS_HASHES,
  OVERWORLD_FIELD_TIMED_PREPARATION_PREDECESSOR_WORLD_HASH,
  AUTHORED_ALBANY_STATION_PREDECESSOR_WORLD_HASH,
];
const MARKET_HASHES = [...STATION_HASHES, AUTHORED_ALBANY_MARKET_PREDECESSOR_WORLD_HASH];
const GREENWAY_HASHES = [...MARKET_HASHES, AUTHORED_ALBANY_GREENWAY_PREDECESSOR_WORLD_HASH];

describe("authored local-scene legacy source epochs", () => {
  it("keeps every generic-copy lifetime cumulative and exact", () => {
    expect([...AUTHORED_ALBANY_WORKS_GENERIC_PREDECESSOR_WORLD_HASHES]).toEqual(WORKS_HASHES);
    expect([...WINTER_RETURN_DOCKET_GENERIC_PREDECESSOR_WORLD_HASHES]).toEqual(CIVIC_HASHES);
    expect([...AUTHORED_ALBANY_CAMPUS_GENERIC_PREDECESSOR_WORLD_HASHES]).toEqual(CAMPUS_HASHES);
    expect([...AUTHORED_ALBANY_STATION_GENERIC_PREDECESSOR_WORLD_HASHES]).toEqual(STATION_HASHES);
    expect([...AUTHORED_ALBANY_MARKET_GENERIC_PREDECESSOR_WORLD_HASHES]).toEqual(MARKET_HASHES);
    expect([...AUTHORED_ALBANY_GREENWAY_GENERIC_PREDECESSOR_WORLD_HASHES]).toEqual(GREENWAY_HASHES);
  });

  it("shares paired event/job fences and derives source support from the registry", () => {
    const eventDefinition = (eventId: string) =>
      AUTHORED_LOCAL_EVENT_LEGACY_DEFINITIONS.find((definition) => definition.eventId === eventId);
    const jobDefinition = (jobId: string) =>
      AUTHORED_LOCAL_JOB_LEGACY_DEFINITIONS.find((definition) => definition.jobId === jobId);

    expect(jobDefinition(AUTHORED_ALBANY_WORKS_JOB_ID)?.acceptedSourceWorldHashes).toBe(
      AUTHORED_ALBANY_WORKS_GENERIC_PREDECESSOR_WORLD_HASHES,
    );
    expect(jobDefinition(AUTHORED_ALBANY_WORKS_JOB_ID)?.canonicalizeLegacyProofSource).toBe(true);
    expect(jobDefinition(AUTHORED_ALBANY_CIVIC_JOB_ID)?.acceptedSourceWorldHashes).toBe(
      WINTER_RETURN_DOCKET_GENERIC_PREDECESSOR_WORLD_HASHES,
    );
    expect(jobDefinition(AUTHORED_ALBANY_CAMPUS_JOB_ID)?.acceptedSourceWorldHashes).toBe(
      AUTHORED_ALBANY_CAMPUS_GENERIC_PREDECESSOR_WORLD_HASHES,
    );
    expect(jobDefinition(AUTHORED_ALBANY_STATION_JOB_ID)?.acceptedSourceWorldHashes).toBe(
      AUTHORED_ALBANY_STATION_GENERIC_PREDECESSOR_WORLD_HASHES,
    );
    expect(eventDefinition(AUTHORED_ALBANY_MARKET_EVENT_ID)?.acceptedSourceWorldHashes).toBe(
      AUTHORED_ALBANY_MARKET_GENERIC_PREDECESSOR_WORLD_HASHES,
    );
    expect(jobDefinition(AUTHORED_ALBANY_MARKET_JOB_ID)?.acceptedSourceWorldHashes).toBe(
      AUTHORED_ALBANY_MARKET_GENERIC_PREDECESSOR_WORLD_HASHES,
    );
    expect(eventDefinition(AUTHORED_ALBANY_GREENWAY_EVENT_ID)?.acceptedSourceWorldHashes).toBe(
      AUTHORED_ALBANY_GREENWAY_GENERIC_PREDECESSOR_WORLD_HASHES,
    );
    expect(jobDefinition(AUTHORED_ALBANY_GREENWAY_JOB_ID)?.acceptedSourceWorldHashes).toBe(
      AUTHORED_ALBANY_GREENWAY_GENERIC_PREDECESSOR_WORLD_HASHES,
    );

    expect(
      authoredLocalJobLegacyDefinitionsForSourceWorldHash(
        OVERWORLD_FIELD_TIMED_PREPARATION_PREDECESSOR_WORLD_HASH,
      ).map((definition) => definition.jobId),
    ).toEqual([
      AUTHORED_ALBANY_STATION_JOB_ID,
      AUTHORED_ALBANY_MARKET_JOB_ID,
      AUTHORED_ALBANY_GREENWAY_JOB_ID,
    ]);
  });
});
